package middlewares

import (
	"errors"
	"net/http"
	"strings"

	"github.com/Aks98068/forensics/internal/models"
	"github.com/Aks98068/forensics/internal/security"
	"github.com/gin-gonic/gin"
	"github.com/golang-jwt/jwt/v5"
	"github.com/google/uuid"
)

// ============================================================
// CONTEXT KEYS
// ============================================================
//
// These constants prevent accidentally using different strings
// in different parts of the application.
//
// Example:
//
//	userID, exists := c.Get(ContextUserID)
//
// ============================================================

const (
	ContextUserID    = "userID"
	ContextUsername  = "username"
	ContextRole      = "role"
	ContextTokenType = "tokenType"
	ContextClaims    = "claims"
)

// ============================================================
// JWT CONFIGURATION
// ============================================================
//
// Keeping these values together makes the middleware easier
// to configure and test.
//
// ============================================================

type JWTAuthConfig struct {
	AccessSecret string

	Issuer   string
	Audience string
}

// ============================================================
// JWT AUTHENTICATION MIDDLEWARE
// ============================================================
//
// This middleware is responsible ONLY for authentication.
//
// It verifies:
//
// 1. Authorization header exists
// 2. Bearer authentication scheme
// 3. Token exists
// 4. Token is not excessively large
// 5. JWT signature
// 6. JWT signing algorithm
// 7. JWT issuer
// 8. JWT audience
// 9. JWT expiration
// 10. JWT issued-at time
// 11. Token ID (jti)
// 12. Token type
// 13. User ID
// 14. Username
// 15. Role
//
// After successful validation, authenticated information is
// stored inside Gin's request context.
//
// ============================================================

func JWTAuthMiddleware(
	config JWTAuthConfig,
) gin.HandlerFunc {

	// --------------------------------------------------------
	// Validate middleware configuration once during startup.
	// --------------------------------------------------------

	config.AccessSecret = strings.TrimSpace(
		config.AccessSecret,
	)

	config.Issuer = strings.TrimSpace(
		config.Issuer,
	)

	config.Audience = strings.TrimSpace(
		config.Audience,
	)

	if config.AccessSecret == "" {
		panic("JWT access secret cannot be empty")
	}

	if config.Issuer == "" {
		panic("JWT issuer cannot be empty")
	}

	if config.Audience == "" {
		panic("JWT audience cannot be empty")
	}

	secret := []byte(config.AccessSecret)

	return func(c *gin.Context) {

		// ====================================================
		// 1. GET AUTHORIZATION HEADER
		// ====================================================

		authHeader := c.GetHeader("Authorization")

		if authHeader == "" {
			unauthorized(c)
			return
		}

		// ====================================================
		// 2. PARSE BEARER SCHEME
		// ====================================================
		//
		// Expected:
		//
		// Authorization: Bearer eyJhbGci...
		//
		// strings.Fields also prevents malformed whitespace
		// from accidentally producing unexpected values.
		//
		// ====================================================

		parts := strings.Fields(authHeader)

		if len(parts) != 2 {
			unauthorized(c)
			return
		}

		if !strings.EqualFold(parts[0], "Bearer") {
			unauthorized(c)
			return
		}

		rawToken := parts[1]

		if rawToken == "" {
			unauthorized(c)
			return
		}

		// ====================================================
		// 3. LIMIT TOKEN SIZE
		// ====================================================
		//
		// JWT access tokens generated by this application are
		// nowhere near this size.
		//
		// This prevents unnecessarily processing abnormally
		// large Authorization values.
		//
		// ====================================================

		const maximumAccessTokenLength = 8192

		if len(rawToken) > maximumAccessTokenLength {
			unauthorized(c)
			return
		}

		// ====================================================
		// 4. CREATE CLAIMS OBJECT
		// ====================================================
		//
		// We reuse the claims definition from security/token.go.
		//
		// DO NOT create another AccessTokenClaims struct here.
		//
		// ====================================================

		claims := &security.AccessTokenClaims{}

		// ====================================================
		// 5. PARSE AND VERIFY JWT
		// ====================================================

		token, err := jwt.ParseWithClaims(
			rawToken,
			claims,

			func(token *jwt.Token) (interface{}, error) {

				// ------------------------------------------------
				// NEVER trust the algorithm supplied by the
				// client.
				//
				// Our application explicitly uses HS256.
				// ------------------------------------------------

				if token.Method != jwt.SigningMethodHS256 {
					return nil, errors.New(
						"unexpected JWT signing method",
					)
				}

				return secret, nil
			},

			// ------------------------------------------------
			// Explicitly allow ONLY HS256.
			// ------------------------------------------------

			jwt.WithValidMethods([]string{
				jwt.SigningMethodHS256.Alg(),
			}),

			// ------------------------------------------------
			// Verify issuer.
			// ------------------------------------------------

			jwt.WithIssuer(config.Issuer),

			// ------------------------------------------------
			// Verify audience.
			// ------------------------------------------------

			jwt.WithAudience(config.Audience),

			// ------------------------------------------------
			// Validate "iat" when present.
			// ------------------------------------------------

			jwt.WithIssuedAt(),
		)

		// ====================================================
		// 6. CHECK PARSING ERROR
		// ====================================================

		if err != nil {
			unauthorized(c)
			return
		}

		// ====================================================
		// 7. CHECK TOKEN VALIDITY
		// ====================================================

		if token == nil || !token.Valid {
			unauthorized(c)
			return
		}

		// ====================================================
		// 8. REQUIRE EXPIRATION
		// ====================================================
		//
		// Access tokens must not be valid indefinitely.
		//
		// Your GenerateAccessToken() already creates ExpiresAt.
		// We explicitly require it here as defense in depth.
		//
		// ====================================================

		if claims.ExpiresAt == nil {
			unauthorized(c)
			return
		}

		// ====================================================
		// 9. REQUIRE ISSUED-AT
		// ====================================================

		if claims.IssuedAt == nil {
			unauthorized(c)
			return
		}

		// ====================================================
		// 10. REQUIRE JWT ID
		// ====================================================
		//
		// Your token generator creates a unique JTI.
		//
		// This becomes useful later for advanced token
		// revocation/auditing.
		//
		// ====================================================

		if strings.TrimSpace(claims.ID) == "" {
			unauthorized(c)
			return
		}

		// ====================================================
		// 11. VALIDATE JWT ID FORMAT
		// ====================================================

		if _, err := uuid.Parse(claims.ID); err != nil {
			unauthorized(c)
			return
		}

		// ====================================================
		// 12. VALIDATE SUBJECT
		// ====================================================
		//
		// Subject should contain the user's UUID.
		//
		// Your token generator sets:
		//
		// Subject: user.ID.String()
		//
		// ====================================================

		if strings.TrimSpace(claims.Subject) == "" {
			unauthorized(c)
			return
		}

		subjectUserID, err := uuid.Parse(
			claims.Subject,
		)

		if err != nil {
			unauthorized(c)
			return
		}

		// The subject and user_id must identify the same user.
		if subjectUserID != claims.UserID {
			unauthorized(c)
			return
		}

		// ====================================================
		// 13. VALIDATE TOKEN TYPE
		// ====================================================
		//
		// This prevents another type of JWT from being accepted
		// as an access token.
		//
		// ====================================================

		if claims.TokenType != "access" {
			unauthorized(c)
			return
		}

		// ====================================================
		// 14. VALIDATE USER ID
		// ====================================================

		if claims.UserID == uuid.Nil {
			unauthorized(c)
			return
		}

		// ====================================================
		// 15. VALIDATE USERNAME
		// ====================================================

		username := strings.TrimSpace(
			claims.Username,
		)

		if username == "" {
			unauthorized(c)
			return
		}

		// ====================================================
		// 16. VALIDATE ROLE
		// ====================================================
		//
		// Never blindly trust an arbitrary role string.
		//
		// Only roles defined by our application are accepted.
		//
		// ====================================================

		if !isValidRole(claims.Role) {
			unauthorized(c)
			return
		}

		// ====================================================
		// 17. STORE AUTHENTICATED IDENTITY
		// ====================================================
		//
		// The handler and later authorization middleware can
		// retrieve these values from Gin's context.
		//
		// ====================================================

		c.Set(
			ContextUserID,
			claims.UserID,
		)

		c.Set(
			ContextUsername,
			username,
		)

		c.Set(
			ContextRole,
			claims.Role,
		)

		c.Set(
			ContextTokenType,
			claims.TokenType,
		)

		c.Set(
			ContextClaims,
			claims,
		)

		// ====================================================
		// 18. CONTINUE REQUEST
		// ====================================================

		c.Next()
	}
}

// ============================================================
// ROLE VALIDATION
// ============================================================

func isValidRole(
	role models.UserRole,
) bool {

	switch role {

	case models.RoleUser,
		models.RoleAnalyst,
		models.RoleAdmin:

		return true

	default:

		return false
	}
}

// ============================================================
// UNAUTHORIZED RESPONSE
// ============================================================
//
// We intentionally return the same external response for
// different authentication failures.
//
// Do NOT tell the client:
//
// - signature failed
// - token expired
// - wrong issuer
// - wrong audience
// - invalid role
// - invalid JTI
//
// Detailed information can be logged internally later.
//
// ============================================================

func unauthorized(
	c *gin.Context,
) {

	c.JSON(
		http.StatusUnauthorized,
		gin.H{
			"error": "unauthorized",
		},
	)

	c.Abort()
}
